// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Token struct {
	// uuid primary key
	Jti      uuid.UUID `json:"jti"`
	Audience string    `json:"audience"`
	Token    string    `json:"token"`
	// expires in should be in seconds
	ExpiresIn   int32     `json:"expires_in"`
	Scope       []string  `json:"scope"`
	Authorities []string  `json:"authorities"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
